### ISSUE TITLE
Can I use this with Play JsObject

### ISSUE THREAD

**Issue by favetelinguis** [hseeberger/akka-http-json#105]
I would like to use this with play default JsObject but not sure if this is possible. This is what i have been trying but getting the message:

could not find implicit value for parameter um.

val json = Unmarshal(response).to[JsObject]

 Are there any default unmarshallers for JsObject and if not how could I make this my selfe?

**Comment by hseeberger** [comment]
This doesn't seem to be an issue. Please ask questions on the Gitter channel. Also notice that you have to provide the full code in question in order for others to understand possible issues.
