### ISSUE TITLE
Add play-json again once Play available for Scala 2.12

### ISSUE THREAD

**Issue by leonardehrenfried** [hseeberger/akka-http-json#108]
http://search.maven.org/#search|ga|1|akka-http-play-json

The latest version on there is 1.10.1. 

Would you be so kind as to publish them?

Thanks!

**Comment by hseeberger** [comment]
Play hasn't yet been released for Scala 2.12 and hence I have disabled this module for the time being.

**Comment by danslapman** [comment]
Now there is one: http://search.maven.org/#artifactdetails%7Ccom.typesafe.play%7Cplay-json_2.12%7C2.6.0-M1%7Cjar
:-)

**Comment by hseeberger** [comment]
Sorry, but I'm not going to release akka-http-json with a dependency on a milestone release.

**Comment by emptyflash** [comment]
Would you consider publishing a snapshot release with a dependency on a milestone version? This way developers can begin developing against 2.12 sooner rather than later.

**Comment by hseeberger** [comment]
Closed via #113. Published to Bintray: 1.11.0-2-g3148b71
