### ISSUE TITLE
How can I get the json with the validation errors for PlayJson

### ISSUE THREAD

**Issue by mrkaspa** [hseeberger/akka-http-json#11]

**Comment by hseeberger** [comment]
Right now not at all. What's your use case? Are you asking for a `FromEntityUnmarshaller[JsResult[A]]`?

**Comment by hseeberger** [comment]
I think this might be useful for you:
- https://github.com/hseeberger/akka-http-json/blob/11-js-result-unmarshaller/akka-http-json-play/src/test/scala/de/heikoseeberger/akkahttpjsonplay/PlayJsonMarshallingSpec.scala#L56
- https://github.com/hseeberger/akka-http-json/blob/11-js-result-unmarshaller/akka-http-json-play/src/test/scala/de/heikoseeberger/akkahttpjsonplay/PlayJsonMarshallingSpec.scala#L62

Let me know if this is what you are asking for.

**Comment by mrkaspa** [comment]
I made this modification to your code => 

```
 /** `FromEntityUnmarshaller` for `application/json` depending on a Play JSON `Reads`. */
  implicit def unmarshaller[A](implicit reads: Reads[A], ec: ExecutionContext, mat: FlowMaterializer): FromEntityUnmarshaller[A] =
    PredefinedFromEntityUnmarshallers
      .stringUnmarshaller
      .forContentTypes(MediaTypes.`application/json`)
      .map(s => {
      val readed = reads.reads(Json.parse(s))
      if (readed.isError)
        readed.recoverTotal {
          e => throw new JsonParseException("JSON Validation error", JsonParseThrowable(Json.obj("messages" -> JsError.toFlatJson(e))))
        }
      readed.get
    })

  /** `ToEntityMarshaller` to `application/json` depending on a Play JSON `Writes`. */
  implicit def marshaller[A](implicit writes: Writes[A]): ToEntityMarshaller[A] =
    PredefinedToEntityMarshallers
      .stringMarshaller(MediaTypes.`application/json`)
      .compose(a => writes.writes(a).toString)

  case class JsonParseException(msg: String, jsonParseThrowable: JsonParseThrowable) extends Exception(msg, jsonParseThrowable)

  case class JsonParseThrowable(errors: JsValue) extends Throwable
```

So I can catch the errors like this:

```
val myRejectionHandler = RejectionHandler.newBuilder()
    .handle {
    case MalformedRequestContentRejection(msg, cause) =>
      complete(StatusCodes.BadRequest, cause.get.asInstanceOf[JsonParseThrowable].errors)
  }.result()

 handleRejections(myRejectionHandler){
....
}
```

**Comment by hseeberger** [comment]
Thanks for the inspiration!

In #13 I applied a similar approach
- Take a look at https://github.com/hseeberger/akka-http-json/blob/11-improve-parse-errors/akka-http-json-play/src/main/scala/de/heikoseeberger/akkahttpjsonplay/PlayJsonMarshalling.scala#L35
- To see that work, execute `akkaHttpJsonPlay/test:run` in sbt, then `curl -i -H 'Content-Type: application/json' -d '{ "wrong": "field" }' 127.0.0.1:8080`

Please let me know if that works for you so I can merge this PR and create a new release.
