### ISSUE TITLE
feature request:  support io.circe.generic.extras.auto._

### ISSUE THREAD

**Issue by onnoll** [hseeberger/akka-http-json#110]
Recently a new package called "extras" was released for Circe, it contains interesting new features like [Configurable Generic Derivation](https://github.com/circe/circe/releases/tag/v0.6.0-RC1) and I was wondering if there is any plan to add support for these new features in this fantastic library.

Thank you.

**Comment by hseeberger** [comment]
You can use any circe library, e.g. generic or extras, simply by adding it to the classpath.
