### ISSUE TITLE
Consider adding features from circe-spray to akka-http-circe

### ISSUE THREAD

**Issue by travisbrown** [hseeberger/akka-http-json#114]
Right now circe-spray includes some features that akka-http-circe doesn't, such as error accumulation, which allows you to easily create an error response that includes all errors in e.g. form input (see the [circe-spray demo](https://github.com/circe/circe/tree/master/examples/todo-spray) for an example).

What do you think, @hseeberger—would you be okay with adding that here as well?

**Comment by hseeberger** [comment]
Excellent idea! Please go for it ;-)

**Comment by hseeberger** [comment]
@travisbrown are you still interested in contributing these features?

**Comment by travisbrown** [comment]
@hseeberger Yep—I can aim to get a PR open this weekend.

**Comment by lomigmegard** [comment]
Had some spare time and created a first PR for this: #127
