### ISSUE TITLE
Using Json4sSupport trait with a RejectionHandler.builder()

### ISSUE THREAD

**Issue by dalegaspi** [hseeberger/akka-http-json#115]
Happy Holidays everyone! :)

probably a basic scala question rather than `akka-http-json` specific...but i'm trying to use this with a `RejectionHandler` and i don't know of an elegant way to use `Json4sSupport` or if it's even possible.  Would like to have some guidance.

thanks!

**Comment by hseeberger** [comment]
Not an issue. For questions please use Gitter.
