### ISSUE TITLE
add fastjson support?

### ISSUE THREAD

**Issue by hepin1989** [hseeberger/akka-http-json#116]
Even it's a Java library:)

**Comment by hseeberger** [comment]
Sure, just send a PR.

**Comment by hepin1989** [comment]
@hseeberger OK,will try later on:)

**Comment by pli2014** [comment]
Enjoy it, Scala does stand on shoulder of Java.

**Comment by hseeberger** [comment]
Closing this, even if a PR would be appreciated.
