### ISSUE TITLE
Continue Support for Scala 2.11

### ISSUE THREAD

**Issue by BusyByte** [hseeberger/akka-http-json#123]
We've just upgraded most of our stack to 2.11 and see that your latest release (1.12.0) is not published in Maven Central.  We've not migrated any of our projects to Scala 2.12 yet and is a sizable effort so it will not come quickly.

Can you please continue to publish releases to Maven Central for Scala 2.11?

**Comment by BusyByte** [comment]
We are using akka-http-circe

**Comment by hseeberger** [comment]
Sync from Bintray to Maven Central didn't work properly. I tried again, hopefully the artifacts show up on Maven Central soon. If not, please use the Bintray resolver shown in the README.
