### ISSUE TITLE
io.circe.generic.extras.auto._

### ISSUE THREAD

**Issue by mazorigal** [hseeberger/akka-http-json#154]
Hi, 

I migrated to the new akka-http-json version, and now looks like that with the new import
 ```import de.heikoseeberger.akkahttpcirce.FailFastCirceSupport._``` and ```import io.circe.generic.extras.auto._``` my code is not compiling and I am getting:
```could not find implicit value for parameter encoder```
however when I replaced it with ```import io.circe.generic.auto._``` , the code compiles.

Any know issues ?

thanks,

**Comment by hseeberger** [comment]
Never used `...extras`. Why would you want to do that?

**Comment by mazorigal** [comment]
well, simply because it have extra stuff :-)
for example 
```implicit val customConfig: Configuration = Configuration.default.withSnakeCaseKeys``` which allow to control how the json keys would look like

**Comment by prascuna** [comment]
@mazorigal not sure if that might help, but this is how I'm getting snake case:

A trait to be mixed in your routes:
https://github.com/prascuna/scala-pills/blob/master/04-sample-rest-service/src/main/scala/scalapills/sample/routes/JsonSupport.scala

and your Configuration inside your DTOs package object
https://github.com/prascuna/scala-pills/blob/master/04-sample-rest-service/src/main/scala/scalapills/sample/models/package.scala

I don't manually import FailFastCirceSupport._

**Comment by hseeberger** [comment]
Is this still an issue?

**Comment by mazorigal** [comment]
@prascuna Thanks,
I would try it.
