### ISSUE TITLE
1.19.0-M2

### ISSUE THREAD

**Issue by yanns** [hseeberger/akka-http-json#174]
Hi, thx for this very useful lib!

sbt-updates seems to find an new version that I cannot find anywhere in the repo.

```
dependencyUpdates
[info] Found 1 dependency update for pim-indexer
[info]   de.heikoseeberger:akka-http-circe : 1.19.0-M1 -> 1.19.0-M2
```

```
$curl https://github.com/hseeberger/akka-http-json/releases/tag/v1.19.0-M2
Not Found
```

Is it an hidden release? 😁

**Comment by hseeberger** [comment]
Oops, I forgot to `git push --tags`. Done now. Thanks for reporting.

**Comment by yanns** [comment]
Thx Heiko!
