### ISSUE TITLE
Version 1.18.0 is not published

### ISSUE THREAD

**Issue by limansky** [hseeberger/akka-http-json#175]
Hi.

It looks like version 1.18.0 was not published to central. 
https://search.maven.org/#search|gav|1|g:"de.heikoseeberger"%20AND%20a:"akka-http-json4s_2.11"

**Comment by hseeberger** [comment]
Duplicate of #172. Use 1.19.0-M2.

**Comment by limansky** [comment]
@hseeberger Is it stable enough, or I should prefer 1.17.0?

**Comment by hseeberger** [comment]
It's using a circe milestone. The rest is stable.
