### ISSUE TITLE
Release 1.18.0 on maven

### ISSUE THREAD

**Issue by mdedetrich** [hseeberger/akka-http-json#176]
It seems that v1.18.0 hasn't actually been released on maven, see https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22de.heikoseeberger%22%20AND%20a%3A%22akka-http-circe_2.11%22

We specifically require v1.18.0 because we need a version that is built against Circe 0.8.0 and where `DecodingFailures` is not inside a private object because we need to access the DecodingFailures exception (i.e. in v 1.17.0 `DecodingFailures` is defined as so)

```scala
private object ErrorAccumulatingUnmarshaller {

  final class DecodingFailures(failures: NonEmptyList[DecodingFailure]) extends Exception {
    override def getMessage = failures.toList.map(_.getMessage).mkString("\n")
  }
}
```

**Comment by mdedetrich** [comment]
I have deployed a version under my own maven in the meantime, 

```sbt
"org.mdedetrich" %% "akka-http-circe" % "1.18.0"
```

**Comment by hseeberger** [comment]
You could also use my Bintray repository (see README).

**Comment by mdedetrich** [comment]
@hseeberger  This isn't on the bintray repo, see

[warn]  module not found: de.heikoseeberger#akka-http-circe_2.11;1.18.0
[warn] ==== local: tried
[warn]   /Users/mdedetrich/.ivy2/local/de.heikoseeberger/akka-http-circe_2.11/1.18.0/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/de/heikoseeberger/akka-http-circe_2.11/1.18.0/akka-http-circe_2.11-1.18.0.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /Users/mdedetrich/.sbt/preloaded/de.heikoseeberger/akka-http-circe_2.11/1.18.0/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////Users/mdedetrich/.sbt/preloaded/de/heikoseeberger/akka-http-circe_2.11/1.18.0/akka-http-circe_2.11-1.18.0.pom
[warn] ==== zalando-nexus-releases: tried
[warn]   https://maven.zalando.net/content/repositories/releases/de/heikoseeberger/akka-http-circe_2.11/1.18.0/akka-http-circe_2.11-1.18.0.pom
[warn] ==== bintray-hseeberger-maven: tried
[warn]   https://dl.bintray.com/hseeberger/maven/de/heikoseeberger/akka-http-circe_2.11/1.18.0/akka-http-circe_2.11-1.18.0.pom
[warn] ==== jcenter: tried
[warn]   https://jcenter.bintray.com/de/heikoseeberger/akka-http-circe_2.11/1.18.0/akka-http-circe_2.11-1.18.0.pom
[info] Resolving com.lucidchart#scalafmt-impl_2.12;1.10-1.0 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: de.heikoseeberger#akka-http-circe_2.11;1.18.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]          de.heikoseeberger:akka-http-circe_2.11:1.18.0 (/Users/mdedetrich/zalando-github/kanadi/build.sbt#L65-80)
[warn]            +- org.zalando:kanadi_2.11:0.1.7

**Comment by hseeberger** [comment]
Please use 1.18.1.
