### ISSUE TITLE
JSON4S pretty printing

### ISSUE THREAD

**Issue by maciej** [hseeberger/akka-http-json#24]
Currently there is no way to parameterise the `json4sMashaller` to make it print pretty JSON. Such output is sometimes useful it printing information for manual inspection.

`Json4sSupport.json4sMarshaller` depends on an implicit `Serialization`, which defines the printing method (either `write` or `writePretty`), so parameterising it the same way as `playJsonMarshaller` is impossible. Do you have an idea how this could be elegantly done?

**Comment by hseeberger** [comment]
Maybe add a `shouldWritePretty: Boolean` parameter to `json4sMarshaller` and `json4sMarshallerConverter` with a default value of `false`, which is used to select which method to invoke.

**Comment by hseeberger** [comment]
Feel free to create a PR ;-)

**Comment by maciej** [comment]
Great! As the `shouldWritePretty` has to be a implicit I think it makes sense to wrap it into a `case class`, as relying on implicit resolution to provide a `Boolean` might lead to some unexpected behaviour. ;-)

**Comment by hseeberger** [comment]
@maciej, have you seen #25? I have published version 0.9.0-ef71c7bede6dd976432f8b4ba2bcdd97cc22c21a to bintray. Please give it a try and let me know if it works for you.

**Comment by maciej** [comment]
@hseeberger awesome, thank you! Using a `sealed abstract class` and `True` and `False` subclasses for `ShouldWritePretty` is a really cool pattern! I feel I've learned something. :-)

**Comment by maciej** [comment]
@hseeberger it works great! Thank you again!
