### ISSUE TITLE
Scala 2.13 support

### ISSUE THREAD

**Issue by ennru** [hseeberger/akka-http-json#253]
I'm not sure which dependencies are missing, but 2.13 things are showing up now...

**Comment by plokhotnyuk** [comment]
@hseeberger please turn on @scala-steward updates for jsoniter-scala, it supports Scala 2.13-RC1 already:

http://repo1.maven.org/maven2/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-macros_2.13.0-RC1/

**Comment by hseeberger** [comment]
PR please, I‘m on vacation 😉

**Comment by 2m** [comment]
PR: https://github.com/hseeberger/akka-http-json/pull/281

**Comment by 2m** [comment]
upickle dropped support for 2.11 when it introduced support for 2.13 in 0.7.5: https://mvnrepository.com/artifact/com.lihaoyi/upickle

@hseeberger are you OK with dropping support for 2.11 when 2.13 is added?

**Comment by hseeberger** [comment]
@2m It is not OK to drop 2.11, it is a MUST! ;-)
Couple of days ago I already looked into bumping the Scala version to 2.13, but some libraries like Circe had not yet been there.

**Comment by plokhotnyuk** [comment]
Is any option to release selected modules for those libraries that were already released for Scala 2.13?

**Comment by hseeberger** [comment]
@plokhotnyuk that is indeed an option, let's do it.

**Comment by 2m** [comment]
PR incoming.

**Comment by hseeberger** [comment]
Closed by #297.
