### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by alex88** [hseeberger/akka-http-json#26]
Hi there,

are there any more complete usage examples for using this to integrate json marshalling for newbies like me?

Thanks!

**Comment by hseeberger** [comment]
Does this help?

https://github.com/hseeberger/reactive-flows/blob/master/src/main/scala/de/heikoseeberger/reactiveflows/HttpService.scala#L55

**Comment by alex88** [comment]
It does, but you're actually using "akka-http-spray-json-experimental" as dependency, not yours "akka-http-json", isn't that supposed to provide (un)marshalling as the akka-http-spray...?

**Comment by hseeberger** [comment]
Sure, but both work the same way: simply import XxxSupport._ and JsonProtocol._ which contains your implicit formats.

**Comment by alex88** [comment]
Ok I'll try again later, thanks for help!
