### ISSUE TITLE
Non Http related Akka dependencies should be marked as provided

### ISSUE THREAD

**Issue by nivox** [hseeberger/akka-http-json#275]
Akka HTTP releases are not tied to a particular Akka version (i.e. the 10.1.x HTTP releases are compatible with the 2.5.x Akka releases) and the user is responsible of providing the actual akka/akka-stream version to be used.

Since this library is mainly tied to a particular akka-http version, it would make sense to mark the other non http related dependencies as provided.

This way a user wanting to adopt this library would only need to find the version compatible with the akka-http version he is running without worrying about the other akka transitive dependencies.

**Comment by hseeberger** [comment]
Makes sense, thanks. PR please 😉

**Comment by Philippus** [comment]
I think this was solved in https://github.com/hseeberger/akka-http-json/pull/446.
