### ISSUE TITLE
Upgrade akka-http-circe to Scala 2.13

### ISSUE THREAD

**Issue by retroryan** [hseeberger/akka-http-json#311]
Hello Heiko!   I was wondering if you have plans for upgrading  akka-http-circe to Scala 2.13? circe 0.12.0-RC1  now supports Scala 2.13 and I tested upgrading akka-http-circe locally and the tests all pass under 2.13.  The only challenge I see is upgrading circe to 0.12.0-RC1 is there is not a version for Scala 2.11 so the Scala 2.11 tests breaks.

**Comment by hseeberger** [comment]
Hello Ryan, There has already been a PR for that, but I do not want to publish depending on milestones or release candidates.

**Comment by retroryan** [comment]
Thanks Heiko for the quick response.  I understand not wanting to depend on milestones or release candidates.  I will check back when a final release is published.

**Comment by ennru** [comment]
Circe 0.12 has just been released... https://github.com/circe/circe/releases

**Comment by plokhotnyuk** [comment]
@ennru JFYK https://github.com/circe/circe/issues/1250

**Comment by plokhotnyuk** [comment]
A PR that includes adding support of Scala 2.13 for akka-http-circe: https://github.com/hseeberger/akka-http-json/pull/324
