### ISSUE TITLE
Unable to import support mixins

### ISSUE THREAD

**Issue by levinotik** [hseeberger/akka-http-json#341]
I've added the relevant json libs as well as `akka-http-circe`as library dependencies and am still unable to identify the imports

`import Json4sSupport._`

when I try compile I get 

```
not found: value Json4sSupport
```

**Comment by hseeberger** [comment]
circe and Json4s are different libraries and such are the respective Akka-http-json libs.

**Comment by levinotik** [comment]
I don't understand your reply. I have also added

```
  "org.json4s" %% "json4s-native" % "3.6.7",
  "org.json4s" %% "json4s-jackson" % "3.6.7"
```

to my dependencies. 

Still unable to import Json4sSupport.

**Comment by plokhotnyuk** [comment]
@levinotik Hi, Levi!

Json4s has not fixed security vulnerabilities, please double-check if it will not affect your business: https://github.com/json4s/json4s/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+denial

**Comment by levinotik** [comment]
@plokhotnyuk Thanks for the heads up. That's not my concern at the moment though. I'm just trying to get circe to work and I'm (clearly) missing something basic. Can't seem to import the support traits at all in spite of adding to my dependencies. My `build.sbt` looks as follows:

```
name := "http-things"

version := "0.1"

scalaVersion := "2.13.1"


libraryDependencies ++= Seq(
  "com.typesafe.akka" %% "akka-stream-testkit" % "2.5.23",
  "com.typesafe.akka" %% "akka-http-testkit" % "10.1.10",
  "com.typesafe.akka" %% "akka-http"   % "10.1.10",
  "com.typesafe.akka" %% "akka-stream" % "2.5.23",
  "org.scalatest" %% "scalatest" % "3.2.0-M1" % Test,
  "org.specs2" %% "specs2-core" % "4.7.1" % Test,
  "org.json4s" %% "json4s-native" % "3.6.7",
  "org.json4s" %% "json4s-jackson" % "3.6.7",
  "de.heikoseeberger" %% "akka-http-circe" % "1.29.1"
)
```

Am I missing something here?

**Comment by plokhotnyuk** [comment]
@levinotik IMHO you should use `import FailFastCirceSupport._` for adding circe support.

**Comment by hseeberger** [comment]
You are importing Akka-http-circe, that‘s the wrong one.

**Comment by levinotik** [comment]
What's the right one? Did I misread the README? It says 


Mix `ArgonautSupport`, `FailFastCirceSupport` or `ErrorAccumulatingCirceSupport`, `JacksonSupport`, `Json4sSupport`, `JsoniterScalaSupport`, `PlayJsonSupport`, `UpickleSupport` or `AvroSupport` into your Akka HTTP code which is supposed to (un)marshal from/to JSON. Don't forget to provide the type class instances for the respective JSON libraries, if needed.

**Comment by levinotik** [comment]
Ohhh I see, there's a `"akka-http-json4s"` artifact. That's very unclear from the README. Thanks.
