### ISSUE TITLE
support for akka 2.6.0

### ISSUE THREAD

**Issue by cheatmenot** [hseeberger/akka-http-json#365]
I have tried to use akka-http-json with akka 2.6.0 but when I try to assemble it (sbt-assembly) it says, it can't because of this version conflicts, Thanks!

[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn]  * com.typesafe.akka:akka-stream_2.12:2.6.0 is selected over 2.5.25
[warn]      +- com.typesafe.akka:akka-persistence_2.12:2.6.0 ()   (depends on 2.6.0)
[warn]      +- com.typesafe.akka:akka-stream-typed_2.12:2.6.0 ()  (depends on 2.6.0)
[warn]      +- com.typesafe.akka:akka-remote_2.12:2.6.0 ()        (depends on 2.6.0)
[warn]      +- de.heikoseeberger:akka-http-circe_2.12:1.29.1      (depends on 2.5.25)

**Comment by hseeberger** [comment]
Which version of akka-http-json did you use?

**Comment by cheatmenot** [comment]
the latest release 1.29.1 - de.heikoseeberger:akka-http-circe_2.12:1.29.1 (depends on 2.5.25)

**Comment by hseeberger** [comment]
Released 1.30.0

**Comment by cheatmenot** [comment]
thanks @hseeberger!
