### ISSUE TITLE
Add circe support

### ISSUE THREAD

**Issue by chuwy** [hseeberger/akka-http-json#37]
[Circe] (https://github.com/PDXostc/rvi_sota_server/tree/master/common/src/main/scala/org/genivi/sota/marshalling) now seems to be very interesting and actively developing JSON library.
I've seen at least [one implementation](https://github.com/PDXostc/rvi_sota_server/tree/master/common/src/main/scala/org/genivi/sota/marshalling) can be used here if @koshelev wouldn't mind.

**Comment by hseeberger** [comment]
Nice. Looking forward to your PR.

**Comment by koshelev** [comment]
@chuwy Sure, I don't mind if you will use the code for a PR.

**Comment by chuwy** [comment]
Cool! Thanks both. I'll send it on this weekend.

**Comment by briantopping** [comment]
Pretty sweet guys! Thanks for all you've done! :+1:
