### ISSUE TITLE
Upgrade to Akka 2.4.2-RC1

### ISSUE THREAD

**Issue by hseeberger** [hseeberger/akka-http-json#44]

**Comment by hseeberger** [comment]
Fixed in #45.

**Comment by fpmk** [comment]
Incorrect version of akka-stream-and-http-experimental, now it's akka-stream-and-http-experimental-**2.0.3**

**Comment by hseeberger** [comment]
No, the latest version of this project follows Akka 2.4.2 which includes Akka Streams/HTTP (i.e. In 2.4.2 they no longer have their own version numbers).

**Comment by fpmk** [comment]
but why they renamed version of akka-http ?
https://github.com/akka/akka/releases

**Comment by hseeberger** [comment]
Please go to the Akka docs and read it up there, e.g. http://akka.io/news/2016/01/26/akka-streams-2.0.3-released.html.
