### ISSUE TITLE
Cross-publish for 2.10

### ISSUE THREAD

**Issue by stanch** [hseeberger/akka-http-json#48]
Could you publish the Scala 2.10 versions of the `1.4.2` modules?

**Comment by hseeberger** [comment]
That's not possible, because Akka 2.4 depends on Java 8 which makes it necessary to build against Scala 2.11 or higher.

**Comment by stanch** [comment]
Could you elaborate? We are using Java 8 with Scala 2.10 just fine...

**Comment by hseeberger** [comment]
Akka 2.4 is compiled against Java 8, i.e. with the scalac option `-target:jvm-1.8`. This library sticks closely to the Akka build settings, hence we can't use Scala 2.10 which doesn't support that target.

**Comment by stanch** [comment]
Got it, thanks!
