### ISSUE TITLE
json4s marshaller also provided for () it seems

### ISSUE THREAD

**Issue by ktoso** [hseeberger/akka-http-json#52]
As found in http://danielasfregola.com/2016/02/07/how-to-build-a-rest-api-with-akka-http/comment-page-1/#comment-236

The confusion:

> Unfortunately, Akka Http resolves complete(Future(())) with an http response with code 200 and empty body — same as complete(Future(None))! Please, put a comment below if you know the rationale behind this design choice.

The reason: http://danielasfregola.com/2016/02/07/how-to-build-a-rest-api-with-akka-http/comment-page-1/#comment-236

It picks up `de.heikoseeberger.akkahttpjson4s.Json4sSupport#json4sMarshaller` for `Unit` as well, causing unexpected outcome. I see it may be tough to change the types around given how this works here but worth pointing out or thinking about perhaps.

**Comment by hseeberger** [comment]
See #49. This is due to Json4s being a crappy library.

**Comment by jrudolph** [comment]
We've stumbled over these kind of things in the past as well (e.g. in https://github.com/spray/spray/issues/990#issuecomment-73480563). One conservative "solution" would be not to provide any reflection-based implicit marshallers automatically at all. Instead, the developer would need to create a little library of domain type marshallers as suggested by @sirthias in the above thread.

I.e. json4sMarshaller is either made not implicit or at least it is not imported and the user then creates tightly scoped implicits with

```scala
implicit def fooFormat = json4sMarshalling[Foo]
```
