### ISSUE TITLE
cannot Unmarshal from String

### ISSUE THREAD

**Issue by strowk** [hseeberger/akka-http-json#528]
I need to unmarshal not only from ResponseEntity using ErrorAccumulatingCirceSupport, but also from String. Is it possible with the same Unmarshal or do I have to use circe directly? Right now it says that there is no implicit from String to my class, I was expecting ErrorAccumulatingCirceSupport to provide such an implicit.

**Comment by hseeberger** [comment]
Look at the implicit unmarshallers defined in `CirceSupport`. As there is one from `ByteString => A`, I think if you provide an implicit `Unmarshaller[String, ByteString]`, it should work. But I am not sure if they compose that way.

**Comment by strowk** [comment]
I ended up using circe directly, seems easier this way
