### ISSUE TITLE
Issue on running under a debugger?

### ISSUE THREAD

**Issue by dalegaspi** [hseeberger/akka-http-json#73]
hi.

Full disclosure: I'm a n00b Scala developer so please bear with me.

I'm running into an issue where the deserialization doesn't seem to be "fast" enough when trying to debug under an IDE (IntelliJ)...basically the code looks like this (I'm using `Json4sSupport`):

```scala
post {
  entity(as[ModuleListRequest]) { m =>
    complete {
      // ... 
      ModuleListResponseType(status = Some(1))
    }
  }
}
```

which runs fine when using `sbt run` or just "Run" under IntelliJ and works beautifully.  However, as soon as run this under a debugger (even without any breakpoints), it doesn't work in the sense that the unmarshalling to `ModuleListRequest` does not complete (will eventually get an HTTP 400 failure because the input is "not recognized".  

If i replace entity with the native `as[JObject]` it's fine and i can unmarshall manually but obviously defeating the purpose of using an automagic unmarshaller.

Not sure if this is an issue using this library or Akka HTTP itself or it's "by design".  some clues/guidance will be greatly appreciated. :)

**Comment by dalegaspi** [comment]
this is crazy...so apparently i'm not doing anything wrong; is is only a problem if you're using an older version of Java 8 (which I am).  This [thread](https://github.com/json4s/json4s/issues/216) explains the whole thing.  

the solution is to either update Java 8 to latest, or use JVM flag `-XX:-EliminateAutoBox`

**Comment by hseeberger** [comment]
I'm glad you figured it out!
