### ISSUE TITLE
Snake case and Camel case support 

### ISSUE THREAD

**Issue by ssemichev** [hseeberger/akka-http-json#77]
How to parse JSON that uses snake case to case class and generate JSON output using snake case?

Let's say my DTO looks like

`case class User(firstName: String, lastName: String)`

**Comment by hseeberger** [comment]
That's not related to akka-http-json, but to one or more of the underlying JSON parser libraries. These usually offer (semi)automatic derivation of encoders/decoders which relies on the exact same spelling as well as the possibility to define encoders/decoders manually – in the latter case you can do arbitrary things.
