### ISSUE TITLE
Not a real issue, have you tried to push this to io.circe?

### ISSUE THREAD

**Issue by menzus** [hseeberger/akka-http-json#81]
Hi,

Thanks for project, it's pretty useful. I wonder why this is not part of the *io.circe* lib?
They have very similar lib for *spray*, it would be great to have some, or at least the *akka-http* there. (https://github.com/travisbrown/circe/tree/master/spray/src/main/scala/io/circe/spray)

Have you tried to fork *io.circe* and push some of these libs?

Thanks,
Tamas

**Comment by hseeberger** [comment]
This project offers marshalling support for various JSON libs, not only Circe.

**Comment by menzus** [comment]
I know, in my question I meant to ask if you've tried to push your code to some of those libs; mainly focused on circe/akka-http.

We're using circe at my company with akka-http. As this support trait is quite few lines of code we decided to write/maintain our marshaller and unmarsahaller as we have a policy to include third party dependencies if they're "really" needed. It's a bit stupid..

I'm sure my company is not the only one with such policies.. I thought it would be useful to have this in circe.

**Comment by hseeberger** [comment]
First, I don't think I want to be concerned about "a bit stupid" company policies. Sorry ;-)

Second and more important, I am very sure circe (and othet JSON libs) should not depend on Akka (HTTP).

**Comment by menzus** [comment]
These are valid points, especially the first :)
Circe already depends on spray.

Anyways, thanks for this project!
