### ISSUE TITLE
Scala FMT

### ISSUE THREAD

**Issue by lomigmegard** [hseeberger/akka-http-json#87]
I am currently working on a PR for this project and I found the newly added formatter very rigid.

Would it be possible to change some settings like for example the `--maxColumn` to something like 100 or 120. 

Also the following code snippet:
```scala
???.recover( _ ⇒ _ ⇒ {
  case MappingException("unknown error", ite: InvocationTargetException) ⇒ 
    throw ite.getCause
})
```

is formatted to:
```scala
???.recover(
  _ ⇒
    _ ⇒ {
      case MappingException("unknown error",
                            ite: InvocationTargetException) ⇒
        throw ite.getCause
    }
)
```

which I personally don't find very readable. What's your opinion on this?

**Comment by hseeberger** [comment]
Well, it's how it works ;-)

Honestly, I'm reluctant to making changes to the formatting settings: scalafmt defines the standard, we follow.

**Comment by lomigmegard** [comment]
I totally get your point, having a formatter is really nice :) 

But scalafmt provides also a lot of options and is still a very young project, I wouldn't say it defines the standard. 

This ticket was just to raise the discussion, it can be closed.

**Comment by hseeberger** [comment]
I consider it a standard ;-)
