### ISSUE TITLE
feature request: debug unmarshallin with json

### ISSUE THREAD

**Issue by antonkulaga** [hseeberger/akka-http-json#90]
It would be nice to also have kind of "debug mode" where I will be able to unmarshal to a tuple (mycaseclass, jsonString)

**Comment by hseeberger** [comment]
Still relevant? If so, please provide more details and of course feel free to submit a PR.

**Comment by kvc-code** [comment]
Yes, still relevant. I have the same need.

**Comment by hseeberger** [comment]
Won't fix.
